<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class ProyectosTemporadasTrabajoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now    =   Carbon::now();
        DB::table('proyectos__temporadas_trabajo')->insert(
            [
                [
                    'id' => 3,
                    'proyecto_id' => 1,
                    'año' => '2002',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 4,
                    'proyecto_id' => 1,
                    'año' => '2008',
                    'numero_temporada' => 'Tercera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 5,
                    'proyecto_id' => 2,
                    'año' => '2002',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 6,
                    'proyecto_id' => 3,
                    'año' => '2001',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 7,
                    'proyecto_id' => 4,
                    'año' => '2001',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 8,
                    'proyecto_id' => 6,
                    'año' => '2002',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 9,
                    'proyecto_id' => 7,
                    'año' => '2002',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 10,
                    'proyecto_id' => 8,
                    'año' => '2003',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 11,
                    'proyecto_id' => 8,
                    'año' => '2004',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 12,
                    'proyecto_id' => 8,
                    'año' => '2005',
                    'numero_temporada' => 'Tercera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 13,
                    'proyecto_id' => 8,
                    'año' => '2010',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 14,
                    'proyecto_id' => 8,
                    'año' => '2005',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 15,
                    'proyecto_id' => 8,
                    'año' => '2006',
                    'numero_temporada' => 'Tercera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 16,
                    'proyecto_id' => 8,
                    'año' => '2007',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 17,
                    'proyecto_id' => 8,
                    'año' => '2008',
                    'numero_temporada' => 'Tercera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 18,
                    'proyecto_id' => 8,
                    'año' => '2006',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 19,
                    'proyecto_id' => 8,
                    'año' => '2012',
                    'numero_temporada' => 'Tercera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 20,
                    'proyecto_id' => 9,
                    'año' => '2003',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 21,
                    'proyecto_id' => 9,
                    'año' => '2007',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 22,
                    'proyecto_id' => 10,
                    'año' => '2003',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 23,
                    'proyecto_id' => 11,
                    'año' => '2003',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 24,
                    'proyecto_id' => 11,
                    'año' => '2006',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 25,
                    'proyecto_id' => 11,
                    'año' => '2005',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 26,
                    'proyecto_id' => 12,
                    'año' => '2003',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 27,
                    'proyecto_id' => 12,
                    'año' => '2007',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 28,
                    'proyecto_id' => 13,
                    'año' => '2004',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 29,
                    'proyecto_id' => 13,
                    'año' => '2005',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 30,
                    'proyecto_id' => 13,
                    'año' => '2006',
                    'numero_temporada' => 'Tercera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 31,
                    'proyecto_id' => 13,
                    'año' => '2007',
                    'numero_temporada' => 'Cuarta',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 32,
                    'proyecto_id' => 14,
                    'año' => '2004',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 33,
                    'proyecto_id' => 15,
                    'año' => '2004',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 34,
                    'proyecto_id' => 16,
                    'año' => '2005',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 35,
                    'proyecto_id' => 17,
                    'año' => '2004',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 36,
                    'proyecto_id' => 19,
                    'año' => '2004',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 37,
                    'proyecto_id' => 19,
                    'año' => '2010',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 38,
                    'proyecto_id' => 20,
                    'año' => '2004',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 39,
                    'proyecto_id' => 21,
                    'año' => '2005',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 40,
                    'proyecto_id' => 22,
                    'año' => '2004',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 41,
                    'proyecto_id' => 22,
                    'año' => '2006',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 42,
                    'proyecto_id' => 22,
                    'año' => '2007',
                    'numero_temporada' => 'Tercera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 43,
                    'proyecto_id' => 22,
                    'año' => '2009',
                    'numero_temporada' => 'Quinta',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 44,
                    'proyecto_id' => 22,
                    'año' => '2008',
                    'numero_temporada' => 'Cuarta',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 45,
                    'proyecto_id' => 22,
                    'año' => '2010',
                    'numero_temporada' => 'Sexta',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 46,
                    'proyecto_id' => 22,
                    'año' => '2011',
                    'numero_temporada' => 'Séptima',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 47,
                    'proyecto_id' => 22,
                    'año' => '2012',
                    'numero_temporada' => 'Octava',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 48,
                    'proyecto_id' => 24,
                    'año' => '2005',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 49,
                    'proyecto_id' => 25,
                    'año' => '2004',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 50,
                    'proyecto_id' => 26,
                    'año' => '2005',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 51,
                    'proyecto_id' => 8,
                    'año' => '2005',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 52,
                    'proyecto_id' => 8,
                    'año' => '2012',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 53,
                    'proyecto_id' => 30,
                    'año' => '2005',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 54,
                    'proyecto_id' => 30,
                    'año' => '2006',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 55,
                    'proyecto_id' => 30,
                    'año' => '2009',
                    'numero_temporada' => 'Tercera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 56,
                    'proyecto_id' => 30,
                    'año' => '2007',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 57,
                    'proyecto_id' => 30,
                    'año' => '2018',
                    'numero_temporada' => 'Cuarta',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 58,
                    'proyecto_id' => 30,
                    'año' => '2018',
                    'numero_temporada' => 'Octava',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 59,
                    'proyecto_id' => 31,
                    'año' => '2005',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 60,
                    'proyecto_id' => 35,
                    'año' => '2005',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 61,
                    'proyecto_id' => 36,
                    'año' => '2005',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 62,
                    'proyecto_id' => 36,
                    'año' => '2010',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 63,
                    'proyecto_id' => 36,
                    'año' => '2010',
                    'numero_temporada' => 'Tercera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 64,
                    'proyecto_id' => 36,
                    'año' => '2006',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 65,
                    'proyecto_id' => 36,
                    'año' => '2012',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 66,
                    'proyecto_id' => 36,
                    'año' => '2012',
                    'numero_temporada' => 'Tercera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 67,
                    'proyecto_id' => 37,
                    'año' => '2005',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 68,
                    'proyecto_id' => 38,
                    'año' => '2006',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 69,
                    'proyecto_id' => 40,
                    'año' => '2006',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 70,
                    'proyecto_id' => 41,
                    'año' => '2006',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 71,
                    'proyecto_id' => 37,
                    'año' => '2006',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 72,
                    'proyecto_id' => 37,
                    'año' => '2010',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 73,
                    'proyecto_id' => 37,
                    'año' => '2011',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 74,
                    'proyecto_id' => 37,
                    'año' => '2011',
                    'numero_temporada' => 'Tercera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 75,
                    'proyecto_id' => 45,
                    'año' => '2007',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 76,
                    'proyecto_id' => 45,
                    'año' => '2006',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 77,
                    'proyecto_id' => 47,
                    'año' => '2007',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 78,
                    'proyecto_id' => 47,
                    'año' => '2009',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 79,
                    'proyecto_id' => 48,
                    'año' => '2010',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 80,
                    'proyecto_id' => 48,
                    'año' => '2007',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 81,
                    'proyecto_id' => 48,
                    'año' => '2008',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 82,
                    'proyecto_id' => 48,
                    'año' => '2009',
                    'numero_temporada' => 'Tercera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 83,
                    'proyecto_id' => 49,
                    'año' => '2007',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 84,
                    'proyecto_id' => 50,
                    'año' => '2007',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 85,
                    'proyecto_id' => 50,
                    'año' => '2010',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 86,
                    'proyecto_id' => 51,
                    'año' => '2007',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 87,
                    'proyecto_id' => 51,
                    'año' => '2008',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 88,
                    'proyecto_id' => 51,
                    'año' => '2009',
                    'numero_temporada' => 'Tercera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 89,
                    'proyecto_id' => 51,
                    'año' => '2009',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 90,
                    'proyecto_id' => 51,
                    'año' => '2008',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 91,
                    'proyecto_id' => 52,
                    'año' => '2005',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 92,
                    'proyecto_id' => 52,
                    'año' => '2006',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 93,
                    'proyecto_id' => 52,
                    'año' => '2008',
                    'numero_temporada' => 'Tercera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 94,
                    'proyecto_id' => 53,
                    'año' => '2008',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 95,
                    'proyecto_id' => 53,
                    'año' => '2010',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 96,
                    'proyecto_id' => 53,
                    'año' => '2011',
                    'numero_temporada' => 'Tercera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 97,
                    'proyecto_id' => 54,
                    'año' => '2008',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 98,
                    'proyecto_id' => 54,
                    'año' => '2010',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 99,
                    'proyecto_id' => 55,
                    'año' => '2008',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 100,
                    'proyecto_id' => 55,
                    'año' => '2010',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 101,
                    'proyecto_id' => 55,
                    'año' => '2011',
                    'numero_temporada' => 'Tercera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 102,
                    'proyecto_id' => 56,
                    'año' => '2008',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 103,
                    'proyecto_id' => 56,
                    'año' => '2009',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 104,
                    'proyecto_id' => 57,
                    'año' => '2011',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 105,
                    'proyecto_id' => 58,
                    'año' => '2008',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 106,
                    'proyecto_id' => 58,
                    'año' => '2009',
                    'numero_temporada' => 'Tercera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 107,
                    'proyecto_id' => 58,
                    'año' => '2007',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 108,
                    'proyecto_id' => 59,
                    'año' => '2007',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 109,
                    'proyecto_id' => 61,
                    'año' => '2011',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 110,
                    'proyecto_id' => 62,
                    'año' => '2009',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 111,
                    'proyecto_id' => 62,
                    'año' => '2010',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 112,
                    'proyecto_id' => 63,
                    'año' => '2011',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 113,
                    'proyecto_id' => 64,
                    'año' => '2010',
                    'numero_temporada' => 'Quinta',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 114,
                    'proyecto_id' => 64,
                    'año' => '2006',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 115,
                    'proyecto_id' => 65,
                    'año' => '2010',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 116,
                    'proyecto_id' => 66,
                    'año' => '2010',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 117,
                    'proyecto_id' => 66,
                    'año' => '2011',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 118,
                    'proyecto_id' => 66,
                    'año' => '2012',
                    'numero_temporada' => 'Tercera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 119,
                    'proyecto_id' => 66,
                    'año' => '2015',
                    'numero_temporada' => 'Sexta',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 120,
                    'proyecto_id' => 67,
                    'año' => '2010',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 121,
                    'proyecto_id' => 67,
                    'año' => '2012',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 122,
                    'proyecto_id' => 68,
                    'año' => '2010',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 123,
                    'proyecto_id' => 69,
                    'año' => '2010',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 124,
                    'proyecto_id' => 72,
                    'año' => '2011',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 125,
                    'proyecto_id' => 75,
                    'año' => '2011',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 126,
                    'proyecto_id' => 75,
                    'año' => '2013',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 127,
                    'proyecto_id' => 75,
                    'año' => '2014',
                    'numero_temporada' => 'Tercera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 128,
                    'proyecto_id' => 76,
                    'año' => '2011',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 129,
                    'proyecto_id' => 77,
                    'año' => '2012',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 130,
                    'proyecto_id' => 78,
                    'año' => '2012',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 131,
                    'proyecto_id' => 79,
                    'año' => '2011',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 132,
                    'proyecto_id' => 79,
                    'año' => '2012',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 133,
                    'proyecto_id' => 79,
                    'año' => '2018',
                    'numero_temporada' => 'Quinta',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 134,
                    'proyecto_id' => 80,
                    'año' => '2011',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 135,
                    'proyecto_id' => 80,
                    'año' => '2013',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 136,
                    'proyecto_id' => 80,
                    'año' => '2014',
                    'numero_temporada' => 'Tercera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 137,
                    'proyecto_id' => 80,
                    'año' => '2015',
                    'numero_temporada' => 'Cuarta',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 138,
                    'proyecto_id' => 80,
                    'año' => '2017',
                    'numero_temporada' => 'Quinta',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 139,
                    'proyecto_id' => 80,
                    'año' => '2018',
                    'numero_temporada' => 'Sexta',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 140,
                    'proyecto_id' => 80,
                    'año' => '2019',
                    'numero_temporada' => 'Séptima',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 141,
                    'proyecto_id' => 81,
                    'año' => '2011',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 142,
                    'proyecto_id' => 81,
                    'año' => '2012',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 143,
                    'proyecto_id' => 81,
                    'año' => '2014',
                    'numero_temporada' => 'Tercera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 144,
                    'proyecto_id' => 81,
                    'año' => '2015',
                    'numero_temporada' => 'Cuarta',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 145,
                    'proyecto_id' => 85,
                    'año' => '2012',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 146,
                    'proyecto_id' => 88,
                    'año' => '2013',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 147,
                    'proyecto_id' => 89,
                    'año' => '2018',
                    'numero_temporada' => 'Tercera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 148,
                    'proyecto_id' => 89,
                    'año' => '2019',
                    'numero_temporada' => 'Cuarta',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 149,
                    'proyecto_id' => 90,
                    'año' => '2014',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 150,
                    'proyecto_id' => 91,
                    'año' => '2013',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 151,
                    'proyecto_id' => 92,
                    'año' => '2014',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 152,
                    'proyecto_id' => 93,
                    'año' => '2014',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 153,
                    'proyecto_id' => 98,
                    'año' => '2014',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 154,
                    'proyecto_id' => 99,
                    'año' => '2014',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 155,
                    'proyecto_id' => 101,
                    'año' => '2015',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 156,
                    'proyecto_id' => 101,
                    'año' => '2016',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 157,
                    'proyecto_id' => 102,
                    'año' => '2015',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 158,
                    'proyecto_id' => 103,
                    'año' => '2015',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 159,
                    'proyecto_id' => 104,
                    'año' => '2016',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 160,
                    'proyecto_id' => 105,
                    'año' => '2016',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 161,
                    'proyecto_id' => 107,
                    'año' => '2016',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 162,
                    'proyecto_id' => 107,
                    'año' => '2017',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 163,
                    'proyecto_id' => 107,
                    'año' => '2018',
                    'numero_temporada' => 'Tercera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 164,
                    'proyecto_id' => 107,
                    'año' => '2018',
                    'numero_temporada' => 'Cuarta',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 165,
                    'proyecto_id' => 109,
                    'año' => '2016',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 166,
                    'proyecto_id' => 110,
                    'año' => '2016',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 167,
                    'proyecto_id' => 111,
                    'año' => '2018',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 168,
                    'proyecto_id' => 112,
                    'año' => '2017',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 169,
                    'proyecto_id' => 112,
                    'año' => '2018',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 170,
                    'proyecto_id' => 115,
                    'año' => '2016',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 171,
                    'proyecto_id' => 119,
                    'año' => '2017',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 172,
                    'proyecto_id' => 120,
                    'año' => '2017',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 173,
                    'proyecto_id' => 120,
                    'año' => '2018',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 174,
                    'proyecto_id' => 120,
                    'año' => '2019',
                    'numero_temporada' => 'Tercera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 175,
                    'proyecto_id' => 121,
                    'año' => '2017',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 176,
                    'proyecto_id' => 122,
                    'año' => '2017',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 177,
                    'proyecto_id' => 122,
                    'año' => '2018',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 178,
                    'proyecto_id' => 123,
                    'año' => '2017',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 179,
                    'proyecto_id' => 123,
                    'año' => '2018',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 180,
                    'proyecto_id' => 125,
                    'año' => '2017',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 181,
                    'proyecto_id' => 126,
                    'año' => '2017',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 182,
                    'proyecto_id' => 126,
                    'año' => '2018',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 183,
                    'proyecto_id' => 127,
                    'año' => '2017',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 184,
                    'proyecto_id' => 127,
                    'año' => '2018',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 185,
                    'proyecto_id' => 127,
                    'año' => '2019',
                    'numero_temporada' => 'Tercera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 186,
                    'proyecto_id' => 129,
                    'año' => '2018',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 187,
                    'proyecto_id' => 130,
                    'año' => '2018',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 188,
                    'proyecto_id' => 130,
                    'año' => '2018',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 189,
                    'proyecto_id' => 130,
                    'año' => '2019',
                    'numero_temporada' => 'Tercera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 190,
                    'proyecto_id' => 130,
                    'año' => '2020',
                    'numero_temporada' => 'Cuarta',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 191,
                    'proyecto_id' => 131,
                    'año' => '2018',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 192,
                    'proyecto_id' => 131,
                    'año' => '2018',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 193,
                    'proyecto_id' => 132,
                    'año' => '2018',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 194,
                    'proyecto_id' => 133,
                    'año' => '2018',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 195,
                    'proyecto_id' => 134,
                    'año' => '2019',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 196,
                    'proyecto_id' => 134,
                    'año' => '2020',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 197,
                    'proyecto_id' => 136,
                    'año' => '2018',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 198,
                    'proyecto_id' => 137,
                    'año' => '2019',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 199,
                    'proyecto_id' => 138,
                    'año' => '2019',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 200,
                    'proyecto_id' => 139,
                    'año' => '2018',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 201,
                    'proyecto_id' => 141,
                    'año' => '2018',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 202,
                    'proyecto_id' => 141,
                    'año' => '2019',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 203,
                    'proyecto_id' => 143,
                    'año' => '2019',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 204,
                    'proyecto_id' => 144,
                    'año' => '2019',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 205,
                    'proyecto_id' => 145,
                    'año' => '2019',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 206,
                    'proyecto_id' => 146,
                    'año' => '2019',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 207,
                    'proyecto_id' => 147,
                    'año' => '2019',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 208,
                    'proyecto_id' => 148,
                    'año' => '2020',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 209,
                    'proyecto_id' => 149,
                    'año' => '2019',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 210,
                    'proyecto_id' => 151,
                    'año' => '2003',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 211,
                    'proyecto_id' => 152,
                    'año' => '2003',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 212,
                    'proyecto_id' => 153,
                    'año' => '2004',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 213,
                    'proyecto_id' => 154,
                    'año' => '2007',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 214,
                    'proyecto_id' => 155,
                    'año' => '2008',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 215,
                    'proyecto_id' => 156,
                    'año' => '2008',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 216,
                    'proyecto_id' => 157,
                    'año' => '2009',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 217,
                    'proyecto_id' => 157,
                    'año' => '2010',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 218,
                    'proyecto_id' => 158,
                    'año' => '2013',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 219,
                    'proyecto_id' => 158,
                    'año' => '2014',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 220,
                    'proyecto_id' => 158,
                    'año' => '2015',
                    'numero_temporada' => 'Tercera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 221,
                    'proyecto_id' => 158,
                    'año' => '2014',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 222,
                    'proyecto_id' => 158,
                    'año' => '2015',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 223,
                    'proyecto_id' => 158,
                    'año' => '2015',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 224,
                    'proyecto_id' => 159,
                    'año' => '2015',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 225,
                    'proyecto_id' => 160,
                    'año' => '2016',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 226,
                    'proyecto_id' => 161,
                    'año' => '2016',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 227,
                    'proyecto_id' => 162,
                    'año' => '2018',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 228,
                    'proyecto_id' => 163,
                    'año' => '2002',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 229,
                    'proyecto_id' => 163,
                    'año' => '2002',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 230,
                    'proyecto_id' => 163,
                    'año' => '2004',
                    'numero_temporada' => 'Tercera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 231,
                    'proyecto_id' => 163,
                    'año' => '2005',
                    'numero_temporada' => 'Cuarta',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 232,
                    'proyecto_id' => 163,
                    'año' => '2006',
                    'numero_temporada' => 'Quinta',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 233,
                    'proyecto_id' => 163,
                    'año' => '2006',
                    'numero_temporada' => 'Sexta',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 234,
                    'proyecto_id' => 163,
                    'año' => '2007',
                    'numero_temporada' => 'Séptima',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 235,
                    'proyecto_id' => 163,
                    'año' => '2008',
                    'numero_temporada' => 'Octava',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 236,
                    'proyecto_id' => 164,
                    'año' => '2004',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 237,
                    'proyecto_id' => 165,
                    'año' => '2005',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 238,
                    'proyecto_id' => 166,
                    'año' => '2006',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 239,
                    'proyecto_id' => 167,
                    'año' => '2005',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 240,
                    'proyecto_id' => 168,
                    'año' => '2010',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 241,
                    'proyecto_id' => 169,
                    'año' => '2011',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 242,
                    'proyecto_id' => 170,
                    'año' => '2012',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 243,
                    'proyecto_id' => 171,
                    'año' => '2013',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 244,
                    'proyecto_id' => 172,
                    'año' => '2015',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 245,
                    'proyecto_id' => 173,
                    'año' => '2015',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 246,
                    'proyecto_id' => 173,
                    'año' => '2015',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 247,
                    'proyecto_id' => 173,
                    'año' => '2021',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 248,
                    'proyecto_id' => 174,
                    'año' => '2016',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 249,
                    'proyecto_id' => 175,
                    'año' => '2020',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 250,
                    'proyecto_id' => 177,
                    'año' => '2017',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 251,
                    'proyecto_id' => 176,
                    'año' => '2015',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 252,
                    'proyecto_id' => 178,
                    'año' => '2017',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 253,
                    'proyecto_id' => 178,
                    'año' => '2018',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 254,
                    'proyecto_id' => 178,
                    'año' => '2020',
                    'numero_temporada' => 'Tercera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 255,
                    'proyecto_id' => 179,
                    'año' => '2019',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 256,
                    'proyecto_id' => 180,
                    'año' => '2020',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 257,
                    'proyecto_id' => 181,
                    'año' => '2005',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 258,
                    'proyecto_id' => 182,
                    'año' => '2018',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 259,
                    'proyecto_id' => 182,
                    'año' => '2019',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 260,
                    'proyecto_id' => 183,
                    'año' => '2003',
                    'numero_temporada' => 'Segunda',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 261,
                    'proyecto_id' => 184,
                    'año' => '2008',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 262,
                    'proyecto_id' => 183,
                    'año' => '2001',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 263,
                    'proyecto_id' => 185,
                    'año' => '2012',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 264,
                    'proyecto_id' => 186,
                    'año' => '2016',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 265,
                    'proyecto_id' => 187,
                    'año' => '2018',
                    'numero_temporada' => 'Primera',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
            ]
        );
    }
}
