name: FTP Upload

on:
  push:
    branches:
      - main

jobs:
  ftp-upload:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install FTP client
      run: choco install filezilla

    - name: Upload files via FTP
      run: |
        $ftpHost = "66.225.201.137"
        $ftpUser = "siiecro1@siiecro.com.mx"
        $ftpPass = ${{ secrets.FTP_ACCESO }}
        $ftpPath = "/path/to/remote/directory"
        $localPath = "${{ github.workspace }}"
        $webclient = New-Object System.Net.WebClient
        $webclient.Credentials = New-Object System.Net.NetworkCredential($ftpUser, $ftpPass)
        $files = Get-ChildItem -Recurse $localPath
        foreach ($file in $files) {
          $relativePath = $file.FullName.Substring($localPath.Length + 1).Replace("\", "/")
          $destination = "$ftpHost/$ftpPath/$relativePath"
          $webclient.UploadFile($destination, $file.FullName)
        }
      shell: powershell
